import rahulImage from '../assets/profile_pics/matrimony_profile_pics/boy_1.png'
import anjaliImage from '../assets/profile_pics/matrimony_profile_pics/girl_1.png'
import meeraImage from '../assets/profile_pics/matrimony_profile_pics/girl_2.png'
import aaravImage from '../assets/profile_pics/matrimony_profile_pics/boy_2.png'
import kabirImage from '../assets/profile_pics/matrimony_profile_pics/boy_3.png'
import ananyaImage from '../assets/profile_pics/matrimony_profile_pics/girl_3.png'

export const heroHighlights = [
  'Verified profiles',
  'Privacy controls',
  'Curated family matching',
  'Dedicated support',
]

export const pillars = [
  {
    title: 'Unwavering Integrity',
    text: 'Every profile begins with trust. We keep the experience serious, verified, and respectful.',
  },
  {
    title: 'Privacy First',
    text: 'Members control what is visible and who can approach, so introductions stay comfortable and intentional.',
  },
  {
    title: 'Sophisticated Matching',
    text: 'Compatibility is guided by family values, career clarity, and long-term life goals.',
  },
]

export const profiles = [

  {
  slug: 'rahul-nair',
  userId: 4,
  name: 'Rahul Nair',
  age: 28,
  role: 'Software Engineer',
  location: 'Bengaluru',
  education: 'Graduate',
  dob: '15 May 1998',
  maritalStatus: 'Never Married',
  motherTongue: 'Malayalam',
  dietaryHabits: 'Vegetarian',
  height: `5'10"`,
  religion: 'Hindu',
  community: 'Nair',
  profession: 'Software Engineer',
  company: 'Infosys',
  income: '₹20L - ₹30L PA',
  familyType: 'Nuclear family',
  fatherOccupation: 'Business',
  motherOccupation: 'Homemaker',
  siblings: '1 younger sister',
  about:
    'Rahul is a calm and family-oriented professional who enjoys a balanced lifestyle. He values honesty, mutual respect, and meaningful relationships.',
  lifestyle: 'Non-smoker, social drinker, active lifestyle',
  interests: ['Travel', 'Photography', 'Fitness', 'Music'],
  partnerPreferences:
    'Looking for a caring and understanding partner who values family, communication, and personal growth.',
  preferredAge: '25 - 30 years',
  preferredHeight: '5\'3" and above',
  preferredEducation: 'Graduate or above',
  preferredLocation: 'Bengaluru, Kochi, Chennai',
  image: rahulImage,
},

{
  slug: 'anjali-menon',
  userId: 10,
  name: 'Anjali Menon',
  age: 27,
  role: 'Doctor',
  location: 'Bengaluru',
  education: 'Medical Professional',
  dob: '10 Mar 1999',
  maritalStatus: 'Never Married',
  motherTongue: 'Malayalam',
  dietaryHabits: 'Vegetarian',
  height: `5'5"`,
  religion: 'Hindu',
  community: 'Nair',
  profession: 'Doctor',
  company: 'ABC Hospital',
  income: '₹15L - ₹25L PA',
  familyType: 'Nuclear family',
  fatherOccupation: 'Business',
  motherOccupation: 'Homemaker',
  siblings: '1 sibling',
  about:
    'Anjali is a caring and ambitious doctor with a warm personality. She values family, meaningful conversations, and a peaceful balanced lifestyle.',
  lifestyle: 'Healthy lifestyle, non-smoker, vegetarian',
  interests: ['Travel', 'Reading', 'Yoga', 'Cooking'],
  partnerPreferences:
    'Looking for a kind, caring and professionally settled partner who values family and mutual respect.',
  preferredAge: '27 - 33 years',
  preferredHeight: '5\'7" and above',
  preferredEducation: 'Graduate or above',
  preferredLocation: 'Bengaluru, Kochi, Chennai',
  image: anjaliImage,
},

{
  slug: 'meera-nair',
  userId: 11,
  name: 'Meera Nair',
  age: 27,
  role: 'IT Professional',
  location: 'Kochi',
  education: 'Graduate',
  dob: '18 Jun 1999',
  maritalStatus: 'Never Married',
  motherTongue: 'Malayalam',
  dietaryHabits: 'Vegetarian',
  height: `5'4"`,
  religion: 'Hindu',
  community: 'Nair',
  profession: 'Software Professional',
  company: 'Technology Company',
  income: '₹12L - ₹18L PA',
  familyType: 'Nuclear family',
  fatherOccupation: 'Retired Professional',
  motherOccupation: 'Homemaker',
  siblings: '1 younger brother',
  about:
    'Meera is a cheerful and family-oriented professional who enjoys travelling, learning new things, and spending quality time with family.',
  lifestyle: 'Non-smoker, vegetarian, active lifestyle',
  interests: ['Travel', 'Reading', 'Music', 'Cooking'],
  partnerPreferences:
    'Looking for a well-mannered and caring partner who values family, trust, and mutual understanding.',
  preferredAge: '27 - 33 years',
  preferredHeight: '5\'7" and above',
  preferredEducation: 'Graduate or above',
  preferredLocation: 'Kochi, Bengaluru, Chennai',
  image: meeraImage,
},
  {
    slug: 'aarav',
    name: 'Aarav',
    age: 29,
    role: 'Product Manager',
    location: 'Bengaluru',
    education: 'IIT Bombay',
    dob: '14 Feb 1997',
    maritalStatus: 'Never Married',
    motherTongue: 'Hindi',
    dietaryHabits: 'Vegetarian',
    height: `5'10"`,
    religion: 'Hindu',
    community: 'Madhwa Brahmin',
    profession: 'Senior Product Manager',
    company: 'FinEdge Labs - Bengaluru',
    income: '₹35L - ₹45L PA',
    familyType: 'Nuclear family',
    fatherOccupation: 'Retired Bank Manager',
    motherOccupation: 'Homemaker',
    siblings: '1 younger sister',
    about:
      'Aarav is a product leader who values family, clarity, and a calm long-term partnership. He enjoys building thoughtful products and keeps his lifestyle simple, disciplined, and balanced.',
    lifestyle: 'Non-smoker, social drinker, active lifestyle',
    interests: ['Travel', 'Reading', 'Fitness', 'Classical music'],
    partnerPreferences:
      'Looking for a warm, grounded partner who values communication, family involvement, and a balanced city life.',
    preferredAge: '26 - 31 years',
    preferredHeight: '5\'3" and above',
    preferredEducation: 'Graduate or above',
    preferredLocation: 'Bengaluru, Mumbai, Pune',
    image: aaravImage,
  },
  
  {
    slug: 'kabir',
    name: 'Kabir',
    age: 31,
    role: 'Architect',
    location: 'Mumbai',
    education: 'Sir JJ College',
    dob: '19 Nov 1994',
    maritalStatus: 'Never Married',
    motherTongue: 'Urdu',
    dietaryHabits: 'Non-vegetarian',
    height: `5'11"`,
    religion: 'Muslim',
    community: 'Khan',
    profession: 'Principal Architect',
    company: 'Studio Linea - Mumbai',
    income: '₹24L - ₹32L PA',
    familyType: 'Joint family',
    fatherOccupation: 'Civil Engineer',
    motherOccupation: 'Professor',
    siblings: '2 sisters',
    about:
      'Kabir is a design-minded professional with a practical outlook and a sincere commitment to building a steady, respectful home life.',
    lifestyle: 'Travel friendly, creative hobbies, fitness focused',
    interests: ['Architecture', 'Photography', 'Football', 'Food'],
    partnerPreferences:
      'Seeking someone who is expressive, respectful, and comfortable with an energetic, family-connected lifestyle.',
    preferredAge: '25 - 31 years',
    preferredHeight: '5\'2" and above',
    preferredEducation: 'Graduate or above',
    preferredLocation: 'Mumbai, Pune, Bangalore',
    image: kabirImage,
  },
  {
    slug: 'ananya',
    name: 'Ananya',
    age: 28,
    role: 'Finance Lead',
    location: 'Delhi',
    education: 'SP Jain',
    dob: '07 Apr 1996',
    maritalStatus: 'Never Married',
    motherTongue: 'Hindi',
    dietaryHabits: 'Eggetarian',
    height: `5'6"`,
    religion: 'Hindu',
    community: 'Kayastha',
    profession: 'Finance Lead',
    company: 'Auric Capital - Delhi',
    income: '₹30L - ₹40L PA',
    familyType: 'Nuclear family',
    fatherOccupation: 'Business Owner',
    motherOccupation: 'School Principal',
    siblings: '1 younger brother',
    about:
      'Ananya is ambitious at work, grounded at home, and values honest communication. She is seeking a partner who respects ambition, family, and shared responsibility.',
    lifestyle: 'Career-focused, balanced routine, occasional travel',
    interests: ['Finance', 'Dancing', 'Books', 'Exploring cafes'],
    partnerPreferences:
      'Looking for a confident, emotionally mature partner who is supportive, family-oriented, and professionally stable.',
    preferredAge: '28 - 34 years',
    preferredHeight: '5\'8" and above',
    preferredEducation: 'MBA / professional degree',
    preferredLocation: 'Delhi NCR, Mumbai, Bengaluru',
    image: ananyaImage,
  },
]

export const stats = [
  ['50k+', 'Verified Members'],
  ['12k+', 'Successful Matches'],
  ['100%', 'Data Security'],
  ['24/7', 'Concierge Desk'],
]
